#!/usr/bin/env python3
"""Generate Portfolio Steward's self-contained runtime protocol projection."""

from __future__ import annotations

import argparse
from hashlib import sha256
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills/project-steward/SKILL.md"
TARGET = ROOT / "skills/portfolio-steward/references/steward-runtime-protocol.md"

PROJECT_DASHBOARD_BLOCK = """看板状态保存在结构化 JSON，并通过脚本生成 HTML：

```bash
python3 scripts/render_dashboard.py path/to/dashboard-state.json path/to/dashboard.html
```

创建或修改状态前读取 [references/dashboard-schema.md](references/dashboard-schema.md)。每次出现实质状态变化时同时：

1. 更新 JSON 并重新生成 HTML，看板与必要的 milestone / `CHANGELOG` 同步；
2. 主动向用户发一条消息，指出哪个 Mission 从什么状态变成什么状态、为什么、下一步是什么。

静默改表不算汇报。没有变化时不要用重复消息打扰用户。"""

PORTFOLIO_DASHBOARD_BLOCK = """大总管的跨仓库状态按 `portfolio-steward/SKILL.md` 与 [飞书组合看板方案](feishu-portfolio-dashboard.md) 维护。每次出现实质状态变化时同时：

1. 更新可追溯的机器事实和当前协作控制面，再刷新 HTML 总览；
2. 主动向用户发一条消息，指出哪个仓库的哪个 Mission 从什么状态变成什么状态、为什么、下一步是什么。

静默改表不算汇报。没有变化时不要用重复消息打扰用户。"""


def slice_between(text: str, start: str, end: str | None = None) -> str:
    start_index = text.index(start)
    end_index = text.index(end, start_index) if end else len(text)
    return text[start_index:end_index].rstrip()


def render(source_text: str) -> str:
    operational = slice_between(source_text, "## 角色\n", "## Prompt Maintenance\n")
    if PROJECT_DASHBOARD_BLOCK not in operational:
        raise ValueError("project dashboard block changed; update the explicit portfolio projection")
    operational = operational.replace(PROJECT_DASHBOARD_BLOCK, PORTFOLIO_DASHBOARD_BLOCK)
    governance = slice_between(source_text, "## 决策边界\n")
    projected = f"{operational}\n\n{governance}\n"
    digest = sha256(projected.encode("utf-8")).hexdigest()
    header = f"""# Steward Runtime Protocol

<!-- AUTO-GENERATED by scripts/sync_runtime_protocol.py; do not edit directly. -->
<!-- source: skills/project-steward/SKILL.md; projection-sha256: {digest} -->

本文件是仓库管家运行协议面向大总管的自包含投影。大总管直接协调跨仓库任务时完整应用下列协议：Mission 必须标注所属仓库，执行 Session 可以是子管家、审查、发布或同步 Session。lineage、隐私、母版发布与飞书规则以 `portfolio-steward/SKILL.md` 的更具体约束为准。

"""
    return header + projected


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated projection is stale")
    args = parser.parse_args()

    expected = render(SOURCE.read_text(encoding="utf-8"))
    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            print(f"stale runtime protocol projection: {TARGET.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("runtime protocol projection is current")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"updated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
